=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping.xsd
<!-- edited with XMLSpy v2022 (x64) (http://www.altova.com) by Jana Brust (Administration Intelligence AG) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
           vc:minVersion="1.1">
    <xs:element name="topic-strategies">
        <xs:annotation>
            <xs:documentation>Comment describing your root element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="strategy">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="Strategy">
                                <xs:attribute name="name" type="xs:string" use="required"/>
                                <xs:attribute name="index" type="xs:int"/>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Parameter">
        <xs:sequence>
            <xs:element name="key" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Strategy">
        <xs:sequence>
            <xs:element name="startPage" type="xs:int" minOccurs="0"/>
            <xs:element name="endPage" type="xs:int" minOccurs="0"/>
            <xs:element name="strategyClass" type="xs:string"/>
            <xs:element name="params" minOccurs="0">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="parameter" type="Parameter"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-base-liturgies.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="Remove Box from Page 328" index="6">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>328</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>136</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Split QS6 of Magiesicht from effect on page 331" index="9">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>331</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>41</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>112</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="End QS6 of Magiesicht with bold line on page 331" index="10">
        <strategyClass>StrategyInsertEmptyBold</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>331</value>
            </parameter>
            <parameter>
                <key>insertAfterLineNo</key>
                <value>41</value>
            </parameter>
            <parameter>
                <key>insertSmall</key>
                <value>true</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Remove Stabschlange from Page 332" index="11">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>332</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>128</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Remove LÃ¶we from Page 335" index="12">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>335</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>56</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>108</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-magic-1-variants.xml
<?xml version="1.1" encoding="UTF-8"?>
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="file:///C:/develop/project/dsa-pdf-reader/src/main/resources/topic-mapping.xsd">
    <strategy name="Add SkillLevel to third Variant of Silentium on Page 162" index="1">
        <strategyClass>StrategyAddTextToLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>162</value>
            </parameter>
            <parameter>
                <key>lineNo</key>
                <value>18</value>
            </parameter>
            <parameter>
                <key>insertAfterPosition</key>
                <value>3</value>
            </parameter>
            <parameter>
                <key>insertText</key>
                <value>16</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Remove start of Rituals on Page 163" index="1">
        <strategyClass>StrategyRemoveSingleLineFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>163</value>
            </parameter>
            <parameter>
                <key>lineNo</key>
                <value>26</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Split Radau from Respondami on Page 161" index="1">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>161</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>28</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>5</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Move Title Radau to end of Page 161" index="1">
        <strategyClass>StrategyPutToEndOfPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>161</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>28</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>28</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Move Zaubererweiterungen-String to end of Page 161" index="1">
        <strategyClass>StrategyPutToEndOfPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>161</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>57</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>57</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Move Variants Radau to end of Page 161" index="1">
        <strategyClass>StrategyPutToEndOfPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>161</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>58</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>65</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-content-gestade.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="StrategyRemoveTextSize" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>5000</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>4900</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>4000</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>3400</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>2700</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>2600</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveTextSize" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>2400</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>2300</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize" index="1">
    <strategyClass>StrategyRemoveTextSize</strategyClass>
    <params>
        <parameter>
            <key>applyToPage</key>
            <value>all</value>
        </parameter>
        <parameter>
            <key>textSize</key>
            <value>2000</value>
        </parameter>
    </params>
</strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-weapons-1-ranged.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="StrategyAddTextToLine - Add Stn to Schleuder on Page 151" index="1">
        <strategyClass>StrategyAddTextToLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>151</value>
            </parameter>
            <parameter>
                <key>lineNo</key>
                <value>52</value>
            </parameter>
            <parameter>
                <key>insertAfterPosition</key>
                <value>3</value>
            </parameter>
            <parameter>
                <key>insertText</key>
                <value>Stn</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-archiv-ausruestung-listen.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">

    <strategy name="StrategyRemoveSingleLineFromPage - I auf 396" index="1">
        <strategyClass>StrategyRemoveSingleLineFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>217</value>
            </parameter>
            <parameter>
                <key>lineNo</key>
                <value>2</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyConcatLinesToFirst - Flasche" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>217</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>196</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>198</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyReplaceStringInLine - Textgröße Flasche">
        <strategyClass>StrategyReplaceStringInLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>217</value>
            </parameter>
            <parameter>
                <key>onLine</key>
                <value>196</value>
            </parameter>
            <parameter>
                <key>size</key>
                <value>900</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveTextSize" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1800</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1200</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1000</value>
            </parameter>
        </params>
    </strategy>


    <strategy name="StrategyReplaceStringInLine - Bannschwert, Dolch ">
        <strategyClass>StrategyReplaceStringInLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>215</value>
            </parameter>
            <parameter>
                <key>onLine</key>
                <value>30</value>
            </parameter>
            <parameter>
                <key>oldText</key>
                <value>Dolche1W6+1GE 1 0</value>
            </parameter>
            <parameter>
                <key>newText</key>
                <value>Dolche1W6+1GE 14 0</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveSingleLineFromPage - Brillantzwergisches Kurzschwert" index="1">
        <strategyClass>StrategyRemoveSingleLineFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>216</value>
            </parameter>
            <parameter>
                <key>lineNo</key>
                <value>65</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyConcatLinesToFirst - Concat Brillantzwegisches Kurzschwert" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>216</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>64</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>66</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyConcatLinesToFirst - Eimer" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>217</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>21</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>23</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyConcatLinesToFirst - Elfendolch" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>217</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>65</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>69</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyConcatLinesToFirst - Federmesser" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>217</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>169</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>172</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyConcatLinesToFirst - Kette" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>219</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>62</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>64</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyConcatLinesToFirst - Kristallkugel" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>219</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>85</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>87</value>
            </parameter>
        </params>
    </strategy>


    <strategy name="StrategyConcatLinesToFirst - Krummdolch" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>219</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>103</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>105</value>
            </parameter>
        </params>
    </strategy>


    <strategy name="StrategyConcatLinesToFirst - Magierkugel" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>219</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>140</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>142</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-hd-flusslande.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="StrategyRemoveTextSize - Topic headlines" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1300</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyReplaceStringInLine - Vorschlaghammer Kampftalent ">
        <strategyClass>StrategyReplaceStringInLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>78</value>
            </parameter>
            <parameter>
                <key>onLine</key>
                <value>28</value>
            </parameter>
            <parameter>
                <key>oldText</key>
                <value>(2H, i)2W6</value>
            </parameter>
            <parameter>
                <key>newText</key>
                <value>(2H, i)Zweihandhiebwaffen2W6</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyConcatLinesToFirst - Concat TÃ¤towierungen" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>88</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>6</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>8</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-gamemaster-shield-abilities.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="topic-mapping.xsd">
    <strategy name="StrategyRemovePages - infos" index="1">
        <strategyClass>StrategyRemovePages</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>14</value>
            </parameter>
            <parameter>
                <key>untilPage</key>
                <value>27</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveTextSize - Topic headlines" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1200</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveTextSize - infos" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>900</value>
            </parameter>
        </params>
    </strategy>


</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-archiv-ausruestung.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="StrategyConcatLinesToFirst - Concat Dreizack" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>93</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>31</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>32</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategySplitLineAfterPosition - Richtschwert">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>128</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>37</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>12</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveLinesFromPage - Referenz Kodex des Schwertes" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>191</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>22</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>
