=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping.xsd
<!-- edited with XMLSpy v2022 (x64) (http://www.altova.com) by Jana Brust (Administration Intelligence AG) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
           vc:minVersion="1.1">
    <xs:element name="topic-strategies">
        <xs:annotation>
            <xs:documentation>Comment describing your root element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="strategy">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="Strategy">
                                <xs:attribute name="name" type="xs:string" use="required"/>
                                <xs:attribute name="index" type="xs:int"/>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Parameter">
        <xs:sequence>
            <xs:element name="key" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Strategy">
        <xs:sequence>
            <xs:element name="startPage" type="xs:int" minOccurs="0"/>
            <xs:element name="endPage" type="xs:int" minOccurs="0"/>
            <xs:element name="strategyClass" type="xs:string"/>
            <xs:element name="params" minOccurs="0">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="parameter" type="Parameter"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-gmuh-streitende-koenigreiche.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
  <strategy name="StrategyRemoveLinesFromPage - emptyLines Waldritter" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>8</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>4</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>5</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveLinesFromPage - emptyLines Seenritter" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>9</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>2</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>3</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveLinesFromPage - emptyLines Mehrer der Macht" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>10</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>4</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>5</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveLinesFromPage - emptyLines Sumudiener" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>11</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>2</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>3</value>
            </parameter>
        </params>
    </strategy>
 </topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-base-spells.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="Switch content on page 296" index="1">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>299</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>28</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>97</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Split QS6 of duplicatus from effect" index="2">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>293</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>50</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>43</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="End QS6 of duplicatus with bold line" index="3">
        <strategyClass>StrategyInsertEmptyBold</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>293</value>
            </parameter>
            <parameter>
                <key>insertAfterLineNo</key>
                <value>50</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Split QS6 of odem arcanum from effect" index="4">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>299</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>7</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>78</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="End QS6 of duplicatus with bold line" index="5">
        <strategyClass>StrategyInsertEmptyBold</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>299</value>
            </parameter>
            <parameter>
                <key>insertAfterLineNo</key>
                <value>7</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-kodex-cleric-waffenliste.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="StrategyRemoveTextSize - Topic headlines" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1800</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize - Topic headlines" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1300</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize - Topic headlines" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1200</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveTextSize - Topic headlines" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1000</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveLinesFromPage - Steinchen" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>424</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>38</value>
            </parameter>

            <parameter>
                <key>untilLine</key>
                <value>39</value>
            </parameter>
        </params>
    </strategy>


    <strategy name="StrategyConcatLinesToFirst - Concat Efferdbart Wurfwaffe" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>424</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>41</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>42</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-magic-3.xml
<?xml version="1.1" encoding="UTF-8"?>
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="file:///C:/develop/project/dsa-pdf-reader/src/main/resources/topic-mapping.xsd">
    <strategy name="Remove Box from Page 131" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>131</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>88</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Split text from QS6 Invinculo on page 134" index="1">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>134</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>57</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>26</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="End QS6 of Invinulo with bold line on page 134" index="10">
        <strategyClass>StrategyInsertEmptyBold</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>134</value>
            </parameter>
            <parameter>
                <key>insertAfterLineNo</key>
                <value>57</value>
            </parameter>
        </params>
    </strategy>
    <!--RITUALS-->
    <strategy name="Switch content on page 141" index="2">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>141</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>3</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>67</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Remove Box from Page 144" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>144</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>88</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-transmutarium.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">

    <strategy name="StrategyReplaceStringInLine - RudelbeschwÃ¶rung ">
        <strategyClass>StrategyReplaceStringInLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>155</value>
            </parameter>
            <parameter>
                <key>onLine</key>
                <value>3</value>
            </parameter>
            <parameter>
                <key>oldText</key>
                <value>Rudelerschaffung I /II / III</value>
            </parameter>
            <parameter>
                <key>newText</key>
                <value>Rudelerschaffung (Transmutationen) I-III</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategySplitLineAfterPosition - AP-Wert">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>155</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>26</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>7</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyReplaceStringInLine Feenfreuend - make Stufe normal">
        <strategyClass>StrategyReplaceStringInLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>155</value>
            </parameter>
            <parameter>
                <key>onLine</key>
                <value>26.1</value>
            </parameter>
            <parameter>
                <key>isBold</key>
                <value>false</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-base-curses.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="Split check of 'Pech an den Hals wünschen' from effect on page 285" index="1">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>285</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>56</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>31</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="End Check of 'Pech an den Hals wünschen' with bold line on page 285" index="2">
        <strategyClass>StrategyInsertEmptyBold</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>285</value>
            </parameter>
            <parameter>
                <key>insertAfterLineNo</key>
                <value>56</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-base-sa-combat.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="Remove PreSAStart from Page 249" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>249</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>55</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>68</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Remove Box Finte from Page 250" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>250</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>71</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>73</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Remove Box Verteidigungshaltung from Page 253" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>253</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>92</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>93</value>
            </parameter>
        </params>
    </strategy>


    <strategy name="StrategyPutToEndOfPage End Column 2 on page 220" index="3">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>220</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>36</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>82</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-cleric-1-ceremonies.xml
<?xml version="1.1" encoding="UTF-8"?>
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="Remove Zwergwal from Page 165" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>165</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>9</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>58</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="Move variant 3 to end of Page 165" index="1">
        <strategyClass>StrategyPutToEndOfPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>165</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>2</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>8</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>
