=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping.xsd
<!-- edited with XMLSpy v2022 (x64) (http://www.altova.com) by Jana Brust (Administration Intelligence AG) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
           vc:minVersion="1.1">
    <xs:element name="topic-strategies">
        <xs:annotation>
            <xs:documentation>Comment describing your root element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="strategy">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="Strategy">
                                <xs:attribute name="name" type="xs:string" use="required"/>
                                <xs:attribute name="index" type="xs:int"/>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Parameter">
        <xs:sequence>
            <xs:element name="key" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Strategy">
        <xs:sequence>
            <xs:element name="startPage" type="xs:int" minOccurs="0"/>
            <xs:element name="endPage" type="xs:int" minOccurs="0"/>
            <xs:element name="strategyClass" type="xs:string"/>
            <xs:element name="params" minOccurs="0">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="parameter" type="Parameter"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-divinarium-blessings.xml
<?xml version="1.1" encoding="UTF-8"?>
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="file:///C:/develop/project/dsa-pdf-reader/src/main/resources/topic-mapping.xsd">

    <strategy name="StrategyRemoveTextSize - PageNumbers" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1500</value>
            </parameter>
        </params>
    </strategy>

</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-grimorium-zhayad.xml
<?xml version="1.1" encoding="UTF-8"?>
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="file:///C:/develop/project/dsa-pdf-reader/src/main/resources/topic-mapping.xsd">
    <strategy name="Zhayad - Rituals" index="2">
        <strategyClass>StrategyInsertLineAfter</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>456</value>
            </parameter>
            <parameter>
                <key>insertAfterLineNo</key>
                <value>3</value>
            </parameter>
            <parameter>
                <key>text</key>
                <value>Transformatio Jal’Widh Agra Esaigra ArcalInvocatio MaximaJal’shezzazim sche-LaurothInvocatio MinorJal’helizim
                    sche-LaurothMeister der ElementeJal’bizbizorimen sche-LaurothNekropathiaJalla’uk Tiiaren KoolPlanastraleInzuul Hoch’auruunRuf der
                    FeenwesenJal’K’zoaStein WandleVizagrasfal sche-LaurothTotes HandleTjaa’asfal Tiaarviz KooljinaarTransmutareCal biz’vizesaiviz
                    IjnauraarWeiches ErstarreWidh Mev’esaigr ArcalWiderwilleIrib Uaraz Jahutiz AarXenographusIribizaar
                </value>
            </parameter>
            <parameter>
                <key>size</key>
                <value>800</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-sunnyshores.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="StrategyRemoveLinesFromPage - Prosa Rüstungen" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>17</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>1</value>
            </parameter>

            <parameter>
                <key>untilLine</key>
                <value>20</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveLinesFromPage - Prosa Rüstungen" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>18</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>1</value>
            </parameter>

            <parameter>
                <key>untilLine</key>
                <value>17</value>
            </parameter>
        </params>
    </strategy>


    <strategy name="StrategyRemovePages - 221 to 252">
        <strategyClass>StrategyRemovePages</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>22</value>
            </parameter>
            <parameter>
                <key>untilPage</key>
                <value>22</value>
            </parameter>
        </params>
    </strategy>
    Monadenschwert Balgringa


    <strategy name="StrategyReplaceStringInLine Feenfreuend - make AP normal">
        <strategyClass>StrategyReplaceStringInLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>23</value>
            </parameter>
            <parameter>
                <key>onLine</key>
                <value>31</value>
            </parameter>
            <parameter>
                <key>oldText</key>
                <value>NameKampftechnikTPL+SAT/PA-ModRWGewichtLängePreisKomplexitätBalgringa</value>
            </parameter>
            <parameter>
                <key>newText</key>
                <value>Monadenschwert BalgringaKomplexitätNameKampftechnikTPL+SAT/PA-ModRWGewichtLängePreisKomplexitätBalgringa</value>
            </parameter>

        </params>
    </strategy>

</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-warringkingdoms-weapon.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="StrategyRemoveLinesFromPage - Kampftechniken" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>10</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>1</value>
            </parameter>

            <parameter>
                <key>untilLine</key>
                <value>20</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-gmuh-sonnenkueste.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="StrategyPutToEndOfPage" index="3">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>15</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>1</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>41</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyPutToEndOfPage" index="3">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>16</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>1</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>9</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyPutToEndOfPage" index="3">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>17</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>1</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>50</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyPutToEndOfPage" index="3">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>18</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>1</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>63</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyPutToEndOfPage" index="3">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>22</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>1</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>68</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyPutToEndOfPage" index="3">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>15</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>1</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>41</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyPutToEndOfPage" index="3">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>25</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>1</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>20</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyPutToEndOfPage" index="3">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>26</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>1</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>32</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyPutToEndOfPage" index="3">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>27</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>1</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>52</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyPutToEndOfPage" index="3">
        <strategyClass>
            StrategyPutToEndOfPage
        </strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>29</value>
            </parameter>
            <parameter>
                <key>startEntryLineNo</key>
                <value>1</value>
            </parameter>
            <parameter>
                <key>endEntryLineNo</key>
                <value>71</value>
            </parameter>
        </params>
    </strategy>





    <strategy name="StrategyConcatLinesToFirst" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>18</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>8</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>10</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyConcatLinesToFirst" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>18</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>21</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>23</value>
            </parameter>
        </params>
    </strategy>

</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-kodex-magic-tradition-skills.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">


    <strategy name="StrategyReplaceStringInLine - Textgröße Melodie der Verwirrung">
        <strategyClass>StrategyReplaceStringInLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>177</value>
            </parameter>
            <parameter>
                <key>onLine</key>
                <value>85</value>
            </parameter>
            <parameter>
                <key>size</key>
                <value>1000</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveTextSize - Topic headlines" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>2300</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveTextSize - Topic headlines" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1700</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveTextSize - Topic headlines" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1600</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveTextSize - Topic headlines" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1500</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveTextSize - Topic headlines" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>1200</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveTextSize - infos" index="1">
        <strategyClass>StrategyRemoveTextSize</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>all</value>
            </parameter>
            <parameter>
                <key>textSize</key>
                <value>900</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyConcatLinesToFirst - Concat Unerschöpflich on Page 4" index="1">
        <strategyClass>StrategyConcatLinesToFirst</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>44</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>29</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>30</value>
            </parameter>
        </params>
    </strategy>


    <strategy name="StrategyRemoveLinesFromPage - Liste" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>44</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>46</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveLinesFromPage - Liste" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>45</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>1</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveLinesFromPage - Liste" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>46</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>46</value>
            </parameter>
        </params>
    </strategy>


    <strategy name="StrategyRemoveLinesFromPage - Liste" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>70</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>1</value>
            </parameter>
            <parameter>
                <key>untilLine</key>
                <value>42</value>
            </parameter>
        </params>
    </strategy>


    <strategy name="StrategyRemoveLinesFromPage - Liste" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>73</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>92</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyReplaceStringInLine - Textgröße Melodie der Verwirrung">
        <strategyClass>StrategyReplaceStringInLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>177</value>
            </parameter>
            <parameter>
                <key>onLine</key>
                <value>84</value>
            </parameter>
            <parameter>
                <key>size</key>
                <value>1000</value>
            </parameter>
        </params>
    </strategy>
</topic-strategies>

=== phofmann1/dsa-pdf-reader/src/main/resources/topic-mapping-hd-wolfsfrost.xml
<topic-strategies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./topic-mapping.xsd">
    <strategy name="StrategyRemoveLinesFromPage" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>16</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>1</value>
            </parameter>

            <parameter>
                <key>untilLine</key>
                <value>53</value>
            </parameter>
        </params>
    </strategy>
    <strategy name="StrategyRemoveLinesFromPage" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>17</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>2</value>
            </parameter>

            <parameter>
                <key>untilLine</key>
                <value>18</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveLinesFromPage" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>19</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>3</value>
            </parameter>

            <parameter>
                <key>untilLine</key>
                <value>12</value>
            </parameter>
        </params>
    </strategy>



    <strategy name="StrategySplitLineAfterPosition" index="1">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>20</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>46</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>54</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategySplitLineAfterPosition" index="1">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>20</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>46.1</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>16</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyReplaceStringInLine">
        <strategyClass>StrategyReplaceStringInLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>20</value>
            </parameter>
            <parameter>
                <key>onLine</key>
                <value>46.1</value>
            </parameter>
            <parameter>
                <key>isBold</key>
                <value>true</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategySplitLineAfterPosition" index="1">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>35</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>14</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>18</value>
            </parameter>
        </params>
    </strategy>


    <strategy name="StrategyRemoveLinesFromPage" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>35</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>14.1</value>
            </parameter>

            <parameter>
                <key>untilLine</key>
                <value>18</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveSingleLineFromPage - I" index="1">
        <strategyClass>StrategyRemoveSingleLineFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>35</value>
            </parameter>
            <parameter>
                <key>lineNo</key>
                <value>70</value>
            </parameter>
        </params>
    </strategy>


    <strategy name="StrategyRemoveLinesFromPage" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>35</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>31</value>
            </parameter>

            <parameter>
                <key>untilLine</key>
                <value>36</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveSingleLineFromPage - I" index="1">
        <strategyClass>StrategyRemoveSingleLineFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>39</value>
            </parameter>
            <parameter>
                <key>lineNo</key>
                <value>119</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategySplitLineAfterPosition" index="1">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>39</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>31</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>53</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategySplitLineAfterPosition" index="1">
        <strategyClass>StrategySplitLineAfterPosition</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>39</value>
            </parameter>
            <parameter>
                <key>splitLine</key>
                <value>31.1</value>
            </parameter>
            <parameter>
                <key>splitAfterPosition</key>
                <value>16</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyReplaceStringInLine">
        <strategyClass>StrategyReplaceStringInLine</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>39</value>
            </parameter>
            <parameter>
                <key>onLine</key>
                <value>31.1</value>
            </parameter>
            <parameter>
                <key>isBold</key>
                <value>true</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveSingleLineFromPage - I auf 396" index="1">
        <strategyClass>StrategyRemoveSingleLineFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>51</value>
            </parameter>
            <parameter>
                <key>lineNo</key>
                <value>55</value>
            </parameter>
        </params>
    </strategy>

    <strategy name="StrategyRemoveLinesFromPage" index="1">
        <strategyClass>StrategyRemoveLinesFromPage</strategyClass>
        <params>
            <parameter>
                <key>applyToPage</key>
                <value>77</value>
            </parameter>
            <parameter>
                <key>fromLine</key>
                <value>34</value>
            </parameter>
        </params>
    </strategy>

</topic-strategies>
